### ISSUE TITLE
Support for unescaping column values

### ISSUE THREAD

**Issue by Mertsch** [nietras/Sep#19]
When I heard about Sep on MS community update I was immediately intrigued and tried some experiments by replacing my existing use of `CsvHelper`. I am very happy with the functionality of CsvHelper, as it does exactly what I need:
Take some text (`string`) and parse it into a `string[][]` of rows and columns.

After adjusting to Seps different way of doing things, I hit a wall when I noticed that there is absolutely no parsing of column values. E.g. `A,"B"` return `A`, `"B"` instead of `A`, `B`.
For me this felt like an oversight (I know it's 0.1 and I do not want to blame anybody).

So my question is, will there ever be a version of Sep that return the **real** content of a column or will it always be raw CSV that needs further parsing?

**Comment by nietras** [comment]
Hi @Mertsch, thanks for trying out Sep. You are right that Sep does not support automatic "escaping" quotes as the documentation also clearly states. I don't have any plans on supporting this at the moment. You might take a look at Sylvan.Data.Csv if performance is important to you. Otherwise, CsvHelper is great of course. 

I will close this as unsupported.

**Comment by nietras** [comment]
Work is well on the way for unescape support and will hopefully come soon.

**Comment by nietras** [comment]
@Mertsch unescaping support has now been merged, I still need to do some finishing touches before a 0.3.0 release with it will happen.

**Comment by nietras** [comment]
https://github.com/nietras/Sep/releases/tag/v0.3.0 has been released. Let me know if anything doesn't work.
